/* Copyright (c) 2026, Yao Zeran
 * 
 * The main book mart layout */


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { MartProvider } from "@/features/mart/context/MartProvider";
import MartHeader from "@/components/MartHeader";
import MartFooter from "@/components/MartFooter";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


type LayoutProps = {
  children: React.ReactNode,
}
const RootLayout: React.FC<LayoutProps> = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MartProvider>
          <MartHeader />
          {children}
          <MartFooter />
        </MartProvider>
      </body>
    </html>
  );
}


export default RootLayout;
